version: '3'
services:
  redis:
    image: redis:5.0.6
    expose:
      - 6379

  nodeapp:
    build:
      context: .
    expose:
      - 3000
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 3000:3000
    command: ['yarn', 'start']
